# Generated by Django 5.0.7 on 2024-08-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_remove_email_timestamp_email_category_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sender_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
